{39528: 0}
{39528: 0.5776151772588491}
{39528: 0.5987878604792058}
{39528: 0.6059350403957069}
{39528: 1.1799613875336945}
{39528: 1.9211367168463767}
{39528: 2.590942889917642}
{39528: 3.3503357362933457}
{39528: 4.101367903407663}
{39528: 4.761432317551225}
{39528: 5.508471490349621}
{39528: 5.9160459181293845}
{39528: 6.564587342087179}
{39528: 6.891857563983649}
{39528: 7.60346437478438}
{39528: 7.971009606961161}
{39528: 8.595268767792732}
{39528: 9.049441158771515}
{39528: 9.657437646761537}
{39528: 10.005037675611675}
{39528: 10.421369757968932}
{39528: 10.861841556616127}
{39528: 11.298636299557984}
{39528: 11.306027071550488}
{39528: 11.670779715292156}
{39528: 12.036174590233713}
{39528: 12.04334802320227}
{39528: 12.050662967376411}
{39528: 12.891009186394513}
{39528: 13.369132694322616}
{39528: 13.37629596143961}
{39528: 11099.57791919075}
{39528: 28409.007529184222}
{39528: 28409.236754818354}
{39528: 28409.240536041092}
{39528: 28410.576976703946}
{39528: 28411.089586594142}
{39528: 28412.236257936805}
Traceback (most recent call last):
  File "ra.py", line 41, in <module>
    vm.verify_full_state()
  File "/ssd//tools/git/RA/vm.py", line 285, in verify_full_state
    self.run()
  File "/ssd//tools/git/RA/vm.py", line 845, in run
    ret = func(s, *funcarg)
  File "/ssd//tools/git/RA/vm.py", line 1438, in op_calldataload
    raise DevelopmentErorr()
exceptions.DevelopmentErorr: Implementation or design error. 
