{47639: 0}
{47639: 0.006678467150777578}
{47639: 0.013157909270375967}
{47639: 0.023232460487633944}
{47639: 0.03278597351163626}
{47639: 0.05415533157065511}
{47639: 0.0636630873195827}
{47639: 0.09422428952530026}
{47639: 0.10372512927278876}
{47639: 0.14268973423168063}
{47639: 0.15234370017424226}
{47639: 0.18671405408531427}
{47639: 0.20274994801729918}
{47639: 0.23704462125897408}
{47639: 0.2579304161481559}
{47639: 0.30131213925778866}
{47639: 0.3338527847081423}
{47639: 0.7825948875397444}
{47639: 0.8992737303487957}
{47639: 1.216736520640552}
{47639: 1.2235303968191147}
{47639: 15890.569729972165}
{47639: 30302.22253288189}
{47639: 30302.438988414593}
{47639: 30302.51431690855}
{47639: 30302.744158357382}
{47639: 30302.96574471332}
{47639: 30303.221513495315}
{47639: 30303.517898859922}
{47639: 30303.747055727057}
{47639: 30303.832905056886}
{47639: 30304.07448835671}
{47639: 30304.078856342938}
{47639: 30305.231851469725}
{47639: 30305.54724872671}
{47639: 30306.778009799775}
Traceback (most recent call last):
  File "ra.py", line 41, in <module>
    vm.verify_full_state()
  File "/ssd//tools/git/RA/vm.py", line 285, in verify_full_state
    self.run()
  File "/ssd//tools/git/RA/vm.py", line 845, in run
    ret = func(s, *funcarg)
  File "/ssd//tools/git/RA/vm.py", line 1438, in op_calldataload
    raise DevelopmentErorr()
exceptions.DevelopmentErorr: Implementation or design error. 
