{45700: 0}
{45700: 0.5476789292879403}
{45700: 0.5670549743808806}
{45700: 0.5732459556311369}
{45700: 1.1225351793691516}
{45700: 1.7904048594646156}
{45700: 2.40797650674358}
{45700: 3.098022284451872}
{45700: 3.7835081326775253}
{45700: 4.394112293608487}
{45700: 5.120073133613914}
{45700: 5.819839472416788}
{45700: 6.45103705348447}
{45700: 6.7668977454304695}
{45700: 7.36013488471508}
{45700: 7.702183319721371}
{45700: 8.335273015778512}
{45700: 8.726613049861044}
{45700: 9.259649456944317}
{45700: 9.554758089128882}
{45700: 10.094972299877554}
{45700: 10.429948871023953}
{45700: 11.59367480687797}
{45700: 11.976500525139272}
{45700: 11.982771784067154}
{45700: 12.760371339973062}
{45700: 13.34230122808367}
{45700: 10325.845252500847}
{45700: 10326.610744507983}
{45700: 20217.14611745486}
{45700: 26946.60325159272}
{45700: 28021.75921155559}
Traceback (most recent call last):
  File "ra.py", line 41, in <module>
    vm.verify_full_state()
  File "/ssd//tools/git/RA/vm.py", line 285, in verify_full_state
    self.run()
  File "/ssd//tools/git/RA/vm.py", line 833, in run
    func, num_inputs, num_output, *funcarg = self.mnemonic_to_func(mnemonic)
  File "/ssd//tools/git/RA/vm.py", line 1191, in mnemonic_to_func
    return d[mnemonic]
KeyError: 'STATICCALL'
