{48842: 0}
{48842: 0.006739793810993433}
{48842: 0.013327227905392647}
{48842: 0.023457243107259274}
{48842: 0.03294497122988105}
{48842: 0.05491052195429802}
{48842: 0.06453637406229973}
{48842: 0.07900705002248287}
{48842: 0.08876103768125176}
{48842: 0.13218081602826715}
{48842: 0.14198437798768282}
{48842: 0.17617389326915145}
{48842: 0.18591382447630167}
{48842: 0.22988320933654904}
{48842: 0.24607139127328992}
{48842: 0.2882075244560838}
{48842: 0.3097727233543992}
{48842: 0.3560795010998845}
{48842: 0.3828551829792559}
{48842: 0.417506355792284}
{48842: 0.4306460628286004}
{48842: 0.782091957051307}
{48842: 1.2581099797971547}
{48842: 1.6168992510065436}
{48842: 1.7444480629637837}
{48842: 2.1018882361240685}
{48842: 2.1084400983527303}
{48842: 3.0384491560980678}
{48842: 3.775805992074311}
{48842: 4.769102123100311}
{48842: 4.775878245010972}
{48842: 5.779019973240793}
{48842: 5.786332612391561}
{48842: 19213.41199973272}
{48842: 19213.881758715957}
{48842: 19214.555386483204}
{48842: 19215.22693198314}
{48842: 19215.714923492167}
{48842: 19217.06565184705}
{48842: 19217.456283617765}
{48842: 19217.460184520576}
{48842: 19217.464171814267}
Traceback (most recent call last):
  File "ra.py", line 41, in <module>
    vm.verify_full_state()
  File "/ssd//tools/git/RA/vm.py", line 285, in verify_full_state
    self.run()
  File "/ssd//tools/git/RA/vm.py", line 833, in run
    func, num_inputs, num_output, *funcarg = self.mnemonic_to_func(mnemonic)
  File "/ssd//tools/git/RA/vm.py", line 1191, in mnemonic_to_func
    return d[mnemonic]
KeyError: 'CODEDATACOPY'
