{37916: 0}
{37916: 0.005953017622232437}
{37916: 0.011449557729065418}
{37916: 0.027608556672930717}
{37916: 0.037679912988096476}
{37916: 0.04679359681904316}
{37916: 0.05580306891351938}
{37916: 0.076626508962363}
{37916: 0.0859132157638669}
{37916: 0.11742413835600019}
{37916: 0.1267460724338889}
{37916: 0.16907627461478114}
{37916: 0.17801927449181676}
{37916: 0.22103500785306096}
{37916: 0.23341293586418033}
{37916: 0.27383558079600334}
{37916: 0.2890988835133612}
{37916: 0.7234349763020873}
{37916: 0.8360186107456684}
{37916: 1.138905898667872}
{37916: 1.145145546644926}
{37916: 1.7976878955960274}
{37916: 2.454798915889114}
{37916: 3.6129405088722706}
Traceback (most recent call last):
  File "ra.py", line 41, in <module>
    vm.verify_full_state()
  File "/ssd//tools/git/RA/vm.py", line 285, in verify_full_state
    self.run()
  File "/ssd//tools/git/RA/vm.py", line 833, in run
    func, num_inputs, num_output, *funcarg = self.mnemonic_to_func(mnemonic)
  File "/ssd//tools/git/RA/vm.py", line 1191, in mnemonic_to_func
    return d[mnemonic]
KeyError: 'CODEDATACOPY'
