{15349: 0}
{15349: 0.57516421796754}
{15349: 0.5955394869670272}
{15349: 0.6021941117942333}
{15349: 1.1770382039248943}
{15349: 1.894876060076058}
{15349: 2.5783299282193184}
{15349: 3.4209738560020924}
{15349: 4.146686566062272}
{15349: 4.853738416451961}
{15349: 5.623975146561861}
{15349: 5.923521678894758}
{15349: 6.573747204616666}
{15349: 6.945753458421677}
{15349: 7.654094719327986}
{15349: 8.022069004364312}
{15349: 8.628160920459777}
{15349: 8.91610432555899}
{15349: 9.521625524386764}
{15349: 9.91697955597192}
{15349: 10.885057851672173}
{15349: 11.235233162995428}
{15349: 11.242524705361575}
{15349: 11.994568883441389}
{15349: 12.711673671379685}
{15349: 7043.392202514224}
{15349: 12902.673631979153}
{15349: 12903.119500878267}
{15349: 12903.12680424843}
{15349: 12903.897490224801}
{15349: 12904.605556849856}
{15349: 12906.9891611957}
{15349: 12909.600860411767}
{15349: 12910.92984492192}
{15349: 12910.937197183724}
{15349: 12912.294181816746}
{15349: 12912.302041910123}
{15349: 12914.042172999121}
{15349: 12915.870977064129}
{15349: 12921.310702824034}
Traceback (most recent call last):
  File "ra.py", line 41, in <module>
    vm.verify_full_state()
  File "/ssd//tools/git/RA/vm.py", line 285, in verify_full_state
    self.run()
  File "/ssd//tools/git/RA/vm.py", line 845, in run
    ret = func(s, *funcarg)
  File "/ssd//tools/git/RA/vm.py", line 1438, in op_calldataload
    raise DevelopmentErorr()
exceptions.DevelopmentErorr: Implementation or design error. 
