pragma directive defines a prior version to 0.5.17. Changing pragma version to 0.5.17....
Traceback (most recent call last):
  File "/bdata2//tools/securify/master/securify2/securify/grammar/attributes/evaluators/evaluator_demand_iterative.py", line 53, in evaluate
    result = super()._execute_rule(rule, arguments)
  File "/bdata2//tools/securify/master/securify2/securify/grammar/attributes/evaluators/evaluator_base.py", line 42, in _execute_rule
    return rule.func(**{name: node for name, node in arguments.items()})
  File "/bdata2//tools/securify/master/securify2/securify/solidity/v_0_5_x/solidity_grammar_core.py", line 318, in cfg
    link_functions(functions, functions_mro)
  File "/bdata2//tools/securify/master/securify2/securify/solidity/v_0_5_x/solidity_utils.py", line 51, in link_functions
    assert block.transfer.dst is not None
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "__main__.py", line 286, in <module>
    main()
  File "__main__.py", line 277, in main
    matches.extend(pattern.find_matches())
  File "/bdata2//tools/securify/master/securify2/securify/analyses/patterns/ir/base_interface_signatures_pattern.py", line 18, in find_matches
    for contract in self.get_cfg().contracts:
  File "/bdata2//tools/securify/master/securify2/securify/analyses/patterns/ir/abstract_ir_pattern.py", line 10, in get_cfg
    cfg = self.analysis_context.cfg
  File "/bdata2//tools/securify/master/securify2/securify/analyses/analysis.py", line 81, in cfg
    self._cfg = self.config.cfg_compiler(self)
  File "__main__.py", line 254, in <lambda>
    cfg_compiler=lambda t: solidity_cfg_compiler.compile_cfg(t.ast).cfg,
  File "/bdata2//tools/securify/master/securify2/securify/solidity/solidity_cfg_compiler.py", line 88, in compile_cfg
    cfg = ast_attr.cfg
  File "/bdata2//tools/securify/master/securify2/securify/grammar/attributes/evaluators/evaluator_demand_base.py", line 84, in __get__
    return self.__evaluator.evaluate(instance, self.__name)
  File "/bdata2//tools/securify/master/securify2/securify/grammar/attributes/evaluators/evaluator_demand_iterative.py", line 57, in evaluate
    f"Rule trace: {self.__rule_trace(dependency_path)}") from e
securify.grammar.attributes.AttributeGrammarError: Error during evaluation of rule 'cfg'. 
Rule trace: 
	SynthesizeRule cfg (File "/bdata2//tools/securify/master/securify2/securify/solidity/v_0_5_x/solidity_grammar_core.py", line 199)
	SynthesizeRule cfg (File "/bdata2//tools/securify/master/securify2/securify/solidity/v_0_5_x/solidity_grammar_core.py", line 272)
